export const ADD_PATIENT_DATA = 'ADD_PATIENT_DATA'
export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA"
export const PATIENT_DATA_ERROR = "PATIENT_DATA_ERROR";
export const PATIENT_DATA_IS_LOADING = "PATIENT_DATA_IS_LOADING";
export const PATIENT_DATA_SUCCESS_CLEAR = "PATIENT_DATA_SUCCESS_CLEAR";
export const FETCH_PATIENT_BLOOD_DATA = "FETCH_PATIENT_BLOOD_DATA";
export const FETCH_PATIENT_TEST_DATA = "FETCH_PATIENT_TEST_DATA";
export const FETCH_PATIENT_SM_DATA = "FETCH_PATIENT_SM_DATA";
export const FETCH_PATIENT_LATEST_TEST_DATA = "FETCH_PATIENT_LATEST_TEST_DATA";

export const UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";
export const USER_ACCOUNT_ERROR = "USER_ACCOUNT_ERROR";
export const USER_ACCOUNT_IS_LOADING = "USER_ACCOUNT_IS_LOADING";
export const UPDATE_USER_PERMISSIONS = "UPDATE_USER_PERMISSIONS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";
export const USER_ACCOUNT_SAVE_SUCCESS = "USER_ACCOUNT_SAVE_SUCCESS";
export const USER_ACCOUNT_CLEAR_SUCCESS = "USER_ACCOUNT_CLEAR_SUCCESS";
export const USER_ACCOUNT_CLEAR_FETCH_SUCCESS = "USER_ACCOUNT_CLEAR_FETCH_SUCCESS";

export const CLIENT_CREDS_LOADING = "CLIENT_CREDS_LOADING";
export const CLIENT_CREDS_ERROR = "CLIENT_CREDS_ERROR";
export const CLIENT_CREDS = "CLIENT_CREDS";

export const IS_LOGGED = "IS_LOGGED";
export const LOGIN_HAS_ERROR = "LOGIN_HAS_ERROR";
export const LOGIN_IS_LOADING = "LOGIN_IS_LOADING";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const CHECK_PERMISSION = "CHECK_PERMISSION";

export const UPDATE_PATIENT_LIST = "UPDATE_PATIENT_LIST"
export const PATIENT_LIST_ERROR = "PATIENT_LIST_ERROR";
export const PATIENT_LIST_IS_LOADING = "PATIENT_LIST_IS_LOADING";

export const UPDATE_SERVER_CONFIG = "UPDATE_SERVER_CONFIG";

export const  UPDATE_HCP_PROFILE = "UPDATE_HCP_PROFILE";
export const  UPDATE_HCP_SEARCH = "UPDATE_HCP_SEARCH";
export const  HCP_DATA_ERROR = "HCP_DATA_ERROR";
export const  HCP_DATA_IS_LOADING = "HCP_DATA_IS_LOADING";
export const  HCP_DATA_SUCCESS_CLEAR = "HCP_DATA_SUCCESS_CLEAR";

