package com.staircase13.apperta.ehrconnector.exception;

import com.staircase13.apperta.service.exception.AppertaJsonException;

import java.util.Map;

/**
 * A generic exception thrown in the case where a call to a remote provider for EHR or demographics fails on the server
 * due to an issue with the request, but not a networking error or issue with server availability.
 */
public class EhrServerException extends AppertaJsonException {

    /**
     * Create a new exception with containing the error code returned from the server and a collection of error messages.
     * @param errorCode The server error code.
     * @param errors The error messages returned from the server.
     */
    public EhrServerException(int errorCode, Map<String,String> errors) {
        super(errorCode, errors);
    }

    /**
     * Create a new exception with containing the error code returned from the serve, a collection of error messages,
     * and a locally generated exception which resulted in this exception being raised.
     * @param errorCode The server error code.
     * @param errors The error messages returned from the server.
     * @param cause An exception generated by the framework in response to the server error.
     */
    public EhrServerException(int errorCode, Map<String,String> errors, Exception cause){
        this(errorCode, errors);
        initCause(cause);
    }
}
