export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const SET_DISPLAY_WEIGHT_IMPERIAL = "SET_DISPLAY_WEIGHT_IMPERIAL";

export const APPOINTMENTS_INFO_SHOWN = "APPOINTMENTS_INFO_SHOWN";
export const GRAPHS_INFO_SHOWN = "GRAPHS_INFO_SHOWN";

export const STORE_USERNAME_LOCAL = "STORE_USERNAME_LOCAL";